### ISSUE TITLE
Possible bug when notifying event watchers?

### ISSUE THREAD

**Issue by MayamaTakeshi** [Ravenstine/goertzeljs#18]
https://github.com/Ravenstine/goertzeljs/blob/dd9b8e9414206d3fb0f57334be6acba5389e2cfe/lib/dtmf.js#L94

In the above line, setTimeout receives the result of execution of handler(value).
But I think it should be:
  setTimeout(function() { handler(value) }, 0);

(tested with node v12.14.1. Maybe there is difference of semantics in older node versions).

**Comment by Ravenstine** [comment]
@MayamaTakeshi You may have stumbled upon something interesting.  The code for DTMF is a relic from my early days of programming, so this is almost certainly a typo on my part, but the strange part is it seems to work correctly when I replicate it:

```javascript
function foo() {
  console.log('foo');
}
```

setTimeout(foo, 0);
console.log('bar');

// bar
// foo
```

The correct behavior is exhibited in every environment I've tried it in.  Yet I don't see documentation describing how this works, but it definitely does.

But you are right in that it should be wrapped in an anonymous function because it's more technically correct.
